baseurl = "https://jongbin.com/"  # End your URL with a `/` trailing slash, e.g. `https://example.com/`.
title = "Jongbin"
copyright = "&copy; 2018 Jongbin Jung"
theme = "minimal"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-88094548-3"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"

[params]
    author = "Jongbin Jung"
    description = "Decisions and Data"
    githubUsername = "jongbinjung"
    accent = "#FB4485"
    showBorder = true
    profilePic = "img/profile.jpg"
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/post/academic"
    name = "Academic"
    weight = 3

[[menu.main]]
    url = "/post/personal"
    name = "Personal"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@jongbin.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jongbinjung/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://scholar.google.com/citations?user=ryQZpjYAAAAJ"
    name = "google"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jongbinjung/"
    name = "linkedin"
    weight = 4

